-- ============================================================
-- DATABASE CHANGES REQUIRED — NOT EXECUTED
-- ============================================================
--
-- This file was generated by Claude for the "Complaint Box"
-- feature. It has NOT been run against your Supabase project.
--
-- It does NOT modify, alter, or delete any existing table.
-- It only ADDS one new table: `complaints`.
--
-- Review this file, then run it yourself in the Supabase SQL
-- editor (or via `supabase db push`) when you're ready.
-- ============================================================

-- ------------------------------------------------------------
-- 1. TABLE
-- ------------------------------------------------------------

create table if not exists public.complaints (
  id                     uuid primary key default gen_random_uuid(),

  -- who filed it (matches auth.users, same pattern as
  -- lost_items.user_id / found_items.user_id elsewhere in the app)
  user_id                uuid not null references auth.users(id) on delete cascade,
  reporter_name          text,
  reporter_email         text,

  -- what kind of complaint
  category               text not null check (
                            category in (
                              'false_claim',
                              'harassment',
                              'item_not_returned',
                              'fake_listing',
                              'bug_or_technical',
                              'other'
                            )
                          ),

  subject                text not null,
  description            text not null,

  -- optional link to a lost/found report the complaint is about
  related_item_type      text check (related_item_type in ('lost', 'found', 'none')) default 'none',
  related_item_reference text,

  -- lifecycle
  status                 text not null default 'open' check (
                            status in ('open', 'in_review', 'resolved', 'dismissed')
                          ),

  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 2. ROW LEVEL SECURITY
-- ------------------------------------------------------------
--
-- Mirrors the privacy pattern already used for contact_requests /
-- match_alerts in this app: a user can only see their own rows.

alter table public.complaints enable row level security;

create policy "Users can insert their own complaints"
  on public.complaints
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can view their own complaints"
  on public.complaints
  for select
  to authenticated
  using (auth.uid() = user_id);

-- No update/delete policy is created for regular users on purpose —
-- once filed, a complaint should not be editable by the person who
-- filed it. Add an admin-only update policy later if/when you build
-- an admin review screen (e.g. gated on a specific user_id or a
-- custom "role" claim).

-- ------------------------------------------------------------
-- 3. INDEX (optional but recommended once you have real traffic)
-- ------------------------------------------------------------

create index if not exists complaints_user_id_idx on public.complaints(user_id);
create index if not exists complaints_status_idx on public.complaints(status);
